import { baseApi } from '@/shared/api/baseApi';
import { supabase } from '@/lib/supabase';
import type { Order, CreateOrderRequest } from '@/types/order';

export const ordersApi = baseApi.injectEndpoints({
    endpoints: (create) => ({
        createOrder: create.mutation<Order, CreateOrderRequest>({
            queryFn: async (orderData) => {
                const { items, ...orderFields } = orderData;

                // Insert order (order_number auto-generated by DB trigger)
                const { data: order, error: orderError } = await supabase
                    .from('orders')
                    .insert({
                        ...orderFields,
                        order_number: '', // Will be set by trigger
                    })
                    .select()
                    .single();

                if (orderError) {
                    return { error: { status: orderError.code, data: orderError.message } };
                }

                // Insert order items
                if (items.length > 0) {
                    const orderItems = items.map((item) => ({
                        order_id: order.id,
                        ...item,
                    }));

                    const { error: itemsError } = await supabase
                        .from('order_items')
                        .insert(orderItems);

                    if (itemsError) {
                        console.error('Error inserting order items:', itemsError);
                    }
                }

                // Fetch the complete order with items
                const { data: fullOrder, error: fetchError } = await supabase
                    .from('orders')
                    .select('*, items:order_items(*)')
                    .eq('id', order.id)
                    .single();

                if (fetchError) {
                    // Return the basic order even if re-fetch fails
                    return { data: order };
                }

                return { data: fullOrder };
            },
            invalidatesTags: ['Orders'],
        }),

        getOrderById: create.query<Order, { id: string }>({
            queryFn: async ({ id }) => {
                const { data, error } = await supabase
                    .from('orders')
                    .select('*, items:order_items(*)')
                    .eq('id', id)
                    .single();

                if (error) {
                    return { error: { status: error.code, data: error.message } };
                }

                return { data };
            },
            providesTags: (_result, _error, { id }) => [{ type: 'Order', id }],
        }),
    }),
    overrideExisting: true,
});

export const { useCreateOrderMutation, useGetOrderByIdQuery } = ordersApi;
